<option value="Afeganistão">Afeganistão</option>
<option value="África do Sul">África do Sul</option>
<option value="Albânia">Albânia</option>
<option value="Alemanha">Alemanha</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Anguilla">Anguilla</option>
<option value="Antártida">Antártida</option>
<option value="Antígua e Barbuda">Antígua e Barbuda</option>
<option value="Arábia Saudita">Arábia Saudita</option>
<option value="Argélia">Argélia</option>
<option value="Argentina">Argentina</option>
<option value="Arménia">Arménia</option>
<option value="Aruba">Aruba</option>
<option value="Austrália">Austrália</option>
<option value="Áustria">Áustria</option>
<option value="Azerbaijão">Azerbaijão</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrein">Bahrein</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbados</option>
<option value="Bélgica">Bélgica</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bermuda">Bermuda</option>
<option value="Bielorrússia">Bielorrússia</option>
<option value="Bolívia">Bolívia</option>
<option value="Bósnia e Herzegovina">Bósnia e Herzegovina</option>
<option value="Botswana">Botswana</option>
<option value="Brasil">Brasil</option>
<option value="Brunei">Brunei</option>
<option value="Bulgária">Bulgária</option>
<option value="Burquina Faso">Burquina Faso</option>
<option value="Burundi">Burundi</option>
<option value="Butão">Butão</option>
<option value="Cabo Verde">Cabo Verde</option>
<option value="Camarões">Camarões</option>
<option value="Camboja">Camboja</option>
<option value="Canadá">Canadá</option>
<option value="Cazaquistão">Cazaquistão</option>
<option value="Ceuta & Melilla">Ceuta & Melilla</option>
<option value="Chade">Chade</option>
<option value="Chile">Chile</option>
<option value="China">China</option>
<option value="Chipre">Chipre</option>
<option value="Cidade do Vaticano">Cidade do Vaticano</option>
<option value="Colômbia">Colômbia</option>
<option value="Comores">Comores</option>
<option value="Congo - Brazzaville">Congo - Brazzaville</option>
<option value="Congo - Kinshasa">Congo - Kinshasa</option>
<option value="Coreia do Norte">Coreia do Norte</option>
<option value="Coreia do Sul">Coreia do Sul</option>
<option value="Costa do Marfim">Costa do Marfim</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Croácia">Croácia</option>
<option value="Cuba">Cuba</option>
<option value="Curaçao">Curaçao</option>
<option value="Diego Garcia">Diego Garcia</option>
<option value="Dinamarca">Dinamarca</option>
<option value="Djibuti">Djibuti</option>
<option value="Dominica">Dominica</option>
<option value="Egipto">Egipto</option>
<option value="El Salvador">El Salvador</option>
<option value="Emirados Árabes Unidos">Emirados Árabes Unidos</option>
<option value="Equador">Equador</option>
<option value="Eritréia">Eritréia</option>
<option value="Eslováquia">Eslováquia</option>
<option value="Eslovénia">Eslovénia</option>
<option value="Espanha">Espanha</option>
<option value="Estados Unidos">Estados Unidos</option>
<option value="Estónia">Estónia</option>
<option value="Etiópia">Etiópia</option>
<option value="Fiji">Fiji</option>
<option value="Filipinas">Filipinas</option>
<option value="Finlândia">Finlândia</option>
<option value="França">França</option>
<option value="Gabão">Gabão</option>
<option value="Gâmbia">Gâmbia</option>
<option value="Gana">Gana</option>
<option value="Geórgia do Sul e Ilhas Sandwich do Sul">Geórgia do Sul e Ilhas Sandwich do Sul</option>
<option value="Geórgia">Geórgia</option>
<option value="Gibraltar">Gibraltar</option>
<option value="Grécia">Grécia</option>
<option value="Grenada">Grenada</option>
<option value="Gronelândia">Gronelândia</option>
<option value="Guadalupe">Guadalupe</option>
<option value="Guam">Guam</option>
<option value="Guatemala">Guatemala</option>
<option value="Guernsey">Guernsey</option>
<option value="Guiana Francesa">Guiana Francesa</option>
<option value="Guiana">Guiana</option>
<option value="Guiné Equatorial">Guiné Equatorial</option>
<option value="Guiné">Guiné</option>
<option value="Guiné-Bissau">Guiné-Bissau</option>
<option value="Haiti">Haiti</option>
<option value="Honduras">Honduras</option>
<option value="Hungria">Hungria</option>
<option value="Ilha da Ascensão">Ilha da Ascensão</option>
<option value="Ilha de Man">Ilha de Man</option>
<option value="Ilha de Natal">Ilha de Natal</option>
<option value="Ilha de Norfolk">Ilha de Norfolk</option>
<option value="Ilhas Åland">Ilhas Åland</option>
<option value="Ilhas Canárias">Ilhas Canárias</option>
<option value="Ilhas Cayman">Ilhas Cayman</option>
<option value="Ilhas Cocos (Keeling)">Ilhas Cocos (Keeling)</option>
<option value="Ilhas Cook">Ilhas Cook</option>
<option value="Ilhas Falkland">Ilhas Falkland</option>
<option value="Ilhas Faroé">Ilhas Faroé</option>
<option value="Ilhas Marianas do Norte">Ilhas Marianas do Norte</option>
<option value="Ilhas Marshall">Ilhas Marshall</option>
<option value="Ilhas Periféricas dos EUA">Ilhas Periféricas dos EUA</option>
<option value="Ilhas Pitcairn">Ilhas Pitcairn</option>
<option value="Ilhas Salomão">Ilhas Salomão</option>
<option value="Ilhas Turcas e Caicos">Ilhas Turcas e Caicos</option>
<option value="Ilhas Virgens Americanas">Ilhas Virgens Americanas</option>
<option value="Ilhas Virgens Britânicas">Ilhas Virgens Britânicas</option>
<option value="Índia">Índia</option>
<option value="Indonésia">Indonésia</option>
<option value="Irão">Irão</option>
<option value="Iraque">Iraque</option>
<option value="Irlanda">Irlanda</option>
<option value="Islândia">Islândia</option>
<option value="Israel">Israel</option>
<option value="Itália">Itália</option>
<option value="Jamaica">Jamaica</option>
<option value="Japão">Japão</option>
<option value="Jersey">Jersey</option>
<option value="Jordânia">Jordânia</option>
<option value="Kiribati">Kiribati</option>
<option value="Kosovo">Kosovo</option>
<option value="Kuwait">Kuwait</option>
<option value="Laos">Laos</option>
<option value="Lesoto">Lesoto</option>
<option value="Letónia">Letónia</option>
<option value="Líbano">Líbano</option>
<option value="Libéria">Libéria</option>
<option value="Líbia">Líbia</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lituânia">Lituânia</option>
<option value="Luxemburgo">Luxemburgo</option>
<option value="Macau SAR China">Macau SAR China</option>
<option value="Macedónia">Macedónia</option>
<option value="Madagascar">Madagascar</option>
<option value="Malásia">Malásia</option>
<option value="Malawi">Malawi</option>
<option value="Maldivas">Maldivas</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Marrocos">Marrocos</option>
<option value="Martinica">Martinica</option>
<option value="Maurício">Maurício</option>
<option value="Mauritânia">Mauritânia</option>
<option value="Mayotte">Mayotte</option>
<option value="México">México</option>
<option value="Micronésia">Micronésia</option>
<option value="Moçambique">Moçambique</option>
<option value="Moldávia">Moldávia</option>
<option value="Mónaco">Mónaco</option>
<option value="Mongólia">Mongólia</option>
<option value="Montenegro">Montenegro</option>
<option value="Montserrat">Montserrat</option>
<option value="Myanmar (Birmânia)">Myanmar (Birmânia)</option>
<option value="Namíbia">Namíbia</option>
<option value="Nauru">Nauru</option>
<option value="Nepal">Nepal</option>
<option value="Nicarágua">Nicarágua</option>
<option value="Níger">Níger</option>
<option value="Nigéria">Nigéria</option>
<option value="Niue">Niue</option>
<option value="Noruega">Noruega</option>
<option value="Nova Caledónia">Nova Caledónia</option>
<option value="Nova Zelândia">Nova Zelândia</option>
<option value="Omã">Omã</option>
<option value="Países Baixos do Caribe">Países Baixos do Caribe</option>
<option value="Países Baixos">Países Baixos</option>
<option value="Palau">Palau</option>
<option value="Panamá">Panamá</option>
<option value="Papua Nova Guiné">Papua Nova Guiné</option>
<option value="Paquistão">Paquistão</option>
<option value="Paraguai">Paraguai</option>
<option value="Peru">Peru</option>
<option value="Polinésia Francesa">Polinésia Francesa</option>
<option value="Polónia">Polónia</option>
<option value="Porto Rico">Porto Rico</option>
<option value="Portugal">Portugal</option>
<option value="Qatar">Qatar</option>
<option value="Quénia">Quénia</option>
<option value="Quirguizistão">Quirguizistão</option>
<option value="Região Administrativa Especial de Hong Kong">Região Administrativa Especial de Hong Kong</option>
<option value="Reino Unido">Reino Unido</option>
<option value="República Centro-Africana">República Centro-Africana</option>
<option value="República Checa">República Checa</option>
<option value="República Dominicana">República Dominicana</option>
<option value="Reunião">Reunião</option>
<option value="Roménia">Roménia</option>
<option value="Ruanda">Ruanda</option>
<option value="Rússia">Rússia</option>
<option value="Saara Ocidental">Saara Ocidental</option>
<option value="Samoa Americana">Samoa Americana</option>
<option value="Samoa">Samoa</option>
<option value="Santa Helena">Santa Helena</option>
<option value="Santa Lúcia">Santa Lúcia</option>
<option value="São Bartolomeu">São Bartolomeu</option>
<option value="São Cristóvão e Nevis">São Cristóvão e Nevis</option>
<option value="São Marinho">São Marinho</option>
<option value="São Martinho">São Martinho</option>
<option value="São Pedro e Miquelon">São Pedro e Miquelon</option>
<option value="São Tomé e Príncipe">São Tomé e Príncipe</option>
<option value="São Vicente e Granadinas">São Vicente e Granadinas</option>
<option value="Senegal">Senegal</option>
<option value="Serra Leoa">Serra Leoa</option>
<option value="Sérvia">Sérvia</option>
<option value="Seychelles">Seychelles</option>
<option value="Singapura">Singapura</option>
<option value="Sint Maarten">Sint Maarten</option>
<option value="Síria">Síria</option>
<option value="Somália">Somália</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Suazilândia">Suazilândia</option>
<option value="Sudão do Sul">Sudão do Sul</option>
<option value="Sudão">Sudão</option>
<option value="Suécia">Suécia</option>
<option value="Suíça">Suíça</option>
<option value="Suriname">Suriname</option>
<option value="Svalbard & Jan Mayen">Svalbard & Jan Mayen</option>
<option value="Tailândia">Tailândia</option>
<option value="Taiwan">Taiwan</option>
<option value="Tajiquistão">Tajiquistão</option>
<option value="Tanzânia">Tanzânia</option>
<option value="Território Britânico do Oceano Índico">Território Britânico do Oceano Índico</option>
<option value="Territórios Franceses do Sul">Territórios Franceses do Sul</option>
<option value="Territórios palestinos">Territórios palestinos</option>
<option value="Timor-Leste">Timor-Leste</option>
<option value="Togo">Togo</option>
<option value="Tokelau">Tokelau</option>
<option value="Tonga">Tonga</option>
<option value="Trinidad & Tobago">Trinidad & Tobago</option>
<option value="Tristão da Cunha">Tristão da Cunha</option>
<option value="Tunísia">Tunísia</option>
<option value="Turquemenistão">Turquemenistão</option>
<option value="Turquia">Turquia</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Ucrânia">Ucrânia</option>
<option value="Uganda">Uganda</option>
<option value="Uruguai">Uruguai</option>
<option value="Uzbequistão">Uzbequistão</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Venezuela">Venezuela</option>
<option value="Vietname">Vietname</option>
<option value="Wallis & Futuna">Wallis & Futuna</option>
<option value="Yemen">Yemen</option>
<option value="Zâmbia">Zâmbia</option>
<option value="Zimbabué">Zimbabué</option>